---
## Pipeline-specific parameters
threads: 80
pychopper: TRUE

# read data
# CDNA or direct RNA reads in fastq format:
raw_fastq: "3166_20190730_hac.fq"
guppy_version: "3.0.6"

# Reference genome:
# genome_fasta could either be (1) a URL to a genome assembly e.g. at enseml / ncbi
#                              (2) a filename corresponding to file that has been placed in the $ReferenceData folder
genome_fasta: "http://ftp.ensembl.org/pub/release-97/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz"
genome_annot: "http://ftp.ensembl.org/pub/release-97/gtf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.97.gtf.gz"
barcodes_fasta: "ReferenceData/teloprime_primers.fas"
genome_id: "R64-1-1.97"

# species database for enrichment with InterMine
mine: "YeastMine"
orgdb: "org.Sc.sgd.db"

# options passed to Pychopper
score_percentile: 98

# options passed to minimap2 during indexing:
minimap_index_opts: "-k14"

# Extra options passed to minimap2:
minimap2_opts: "-uf"  # required for stranded data e.g. when pychopper filtered

# Minmum mapping quality:
minimum_mapping_quality: 10

# Options passed to spliced_bam2gff:
spliced_bam2gff_opts: "-s"  # required for stranded data e.g. when pychopper filtered

# -c parameter:
minimum_cluster_size: 10

# -p parameter:
minimum_isoform_percent: 1.0

# -d parameter:
exon_boundary_tolerance: 10

# -e parameter:
terminal_exon_boundary_tolerance: 30

# Extra options passed to minimap2 when mapping polished reads:
minimap2_opts_polished: "-uf"   # required for stranded data e.g. when pychopper filtered

# Options passed to spliced_bam2gff when converting alignments of polished reads:
spliced_bam2gff_opts_pol: "-s"  # required for stranded data e.g. when pychopper filtered

# Options passed to collapse_partials when collapsing fragmentation artifacts
# Internal exon boundary tolerance:
collapse_internal_tol: 5

# Five prime boundary tolerance:
collapse_five_tol: 5000

# Three prime boundary tolerance:
collapse_three_tol: 30

# how many top expressed genes to consider for enrichment
topexp: 100

## Add user custom text parts to the report:
UserText: TRUE

